### ISSUE TITLE
Scale problem

### ISSUE THREAD

**Issue by AldeRoberge** [tojynick/Stylized-Water-Shader-Unity-URP#1]
When scaling it up (2x+) it seems like the waves get bigger and bigger. How would I use this for an ocean?

**Comment by tojynick** [comment]
Hi, thanks for reporting! I usually use pro builder mesh with a uniform scale to make large areas of water, but I will try to modify the shader in such a way that scaling won't affect wave size.

**Comment by AldeRoberge** [comment]
Hello! Thanks for the quick response. I think this would be the best option, considering the mesh stays the same (no added triangles) instead of a mesh with a higher level of detail.

**Comment by tojynick** [comment]
Hi again! I fixed the scale problem. Now waves stay the same size when the mesh is scaled up. It works only if you perform uniform scaling though.
